export const types = {
    // app types
    FETCH_START: 'FETCH_START',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAIL: 'FETCH_FAIL',

    // article types
    GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
    ADD_ARTICLE: 'ADD_ARTICLE',
    GET_ARTICLE_DETAIL: 'GET_ARTICLE_DETAIL',
    GET_HOT_ARTICLE_LIST: 'GET_HOT_ARTICLE_LIST',
    GET_TIMELINE_ARTICLE_LIST: 'GET_TIMELINE_ARTICLE_LIST',

    // comment types
    ADD_COMMENT: 'ADD_COMMENT',
    GET_COMMENT_LIST: 'GET_COMMENT_LIST',

    // user types
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    GET_USER: 'GET_USER'
}